### ISSUE TITLE
mapped region in DCPMMMmapFile never unmap

### ISSUE THREAD

**Issue by starkwj** [pmem/pmem-rocksdb#3]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

In DCPMMMmapFile:
Memory regions mapped by MapNewRegion() are never unmapped.
UnmapCurrentRegion() is not implemented and not called when map new region or close the file.
https://github.com/pmem/pmem-rocksdb/blob/b667ce50f4115872ee25ce741a2c70b4b1dee409/env/env_dcpmm.cc#L58-L60

### Actual behavior
When running pmem-rocksdb with large volumn of data, pmem_map_file() in MapNewRegion() failed because the mapped regions are too much.
https://github.com/pmem/pmem-rocksdb/blob/b667ce50f4115872ee25ce741a2c70b4b1dee409/env/env_dcpmm.cc#L77-L83

**Comment by JiayuZzz** [comment]
Sorry for delay response, fixed #4
